name: "Go Coverage"
on:
  pull_request:
    branches:
      # It's important that the action also runs on merge to main
      - v4
jobs:
  coverage:
    name: Update coverage badge
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v4
        with:
          go-version: '1.16'

      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Run Test
        run: |
          go test -v ./... -coverprofile=coverage.out

      - uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: coverage.out